#+TITLE:     Q-Translate API Reference
#+AUTHOR:    Dashamir Hoxha
#+EMAIL:     dashohoxha@gmail.com
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:nil toc:t \n:nil @:t ::t |:t ^:nil -:t f:t *:t <:t
#+OPTIONS:   TeX:nil LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:overview toc:t ltoc:t mouse:#aadddd buttons:0 path:org-info.js
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="org-info.css" />

* report


** stats

   General statistics (number of likes and translations) for the last
   week, month and year.

   + GET api/report/stats ::
     - lng :: language of translations

   + POST api/report/stats ::
     - lng :: language of translations


   Examples:
   - [[https://dev.qtranslate.org/api-examples-php/report/stats.php]]
   - [[http://info.qtranslate.org/api-examples-js/#report/stats_get.js]]
   - [[http://info.qtranslate.org/api-examples-js/#report/stats_post.js]]

   #+begin_example
   curl -H 'Accept: application/json' \
        'https://qtranslate.org/api/report/stats?lng=en' | python -m json.tool
   curl -H 'Content-type: application/json' \
        -X POST https://qtranslate.org/api/report/stats \
        -d '{"lng": "sq"}' | python -m json.tool
   #+end_example


** topusers

   Statistics about top contributing users.

   + GET api/report/topcontrib ::
     - lng :: language of translations
     - period :: period of report (last =day | week | month | year=)
     - size :: number of results (top contributers), between 5 and 100

   + POST api/report/topcontrib ::
     - lng :: language of translations
     - period :: period of report (last =day | week | month | year=)
     - size :: number of results (top contributers), between 5 and 100

   Examples:
   - [[https://dev.qtranslate.org/api-examples-php/report/topusers.php]]
   - [[http://info.qtranslate.org/api-examples-js/#report/topusers_get.js]]
   - [[http://info.qtranslate.org/api-examples-js/#report/topusers_post.js]]

   #+begin_example
   curl -H 'Accept: application/json' \
        'https://qtranslate.org/api/report/topusers?lng=en&period=week' \
        | python -m json.tool
   curl -H 'Accept: application/json' -H 'Content-type: application/json' \
        -X POST https://qtranslate.org/api/report/topusers \
        -d '{"lng": "en", "period": "week", "size": 10}' \
        | python -m json.tool
   #+end_example


* translations

** get

   Get a verse, along with its translations, likes and other details.

   + GET api/translations/$selector ::
     - selector :: Translation selector, in the form: chapter,verse,lng

   + POST api/translations/get ::
     - chapter :: Chapter number.
     - verse :: Verse number.
     - lng :: The language of translations, like en, fr, de, etc.

   Examples:
   - [[http://info.qtranslate.org/api-examples-js/#translations/retrieve.js]]
   - [[http://info.qtranslate.org/api-examples-js/#translations/get.js]]
   - [[https://dev.qtranslate.org/api-examples-php/translations/get.php]]

   #+BEGIN_EXAMPLE
   curl -H 'Accept: application/json' \
        'https://dev.qtranslate.org/api/translations/2,3,sq' \
        | python -m json.tool
   curl -H 'Content-type: application/json' \
        -X POST https://qtranslate.org/api/translations/get
        -d '{"chapter": "2", "verse": "3", "lng": "en"}' \
        | python -m json.tool
   #+END_EXAMPLE


** add

   Add a new translation to a source string.

   + POST api/translations/add ::
     - sguid ::
         The string ID for which a new translation should be added.
     - lng ::
         The language (code) of the new translation.
     - translation ::
         The new translation as a string. If the string has plural
         version(s) as well, they are concatenated with NULL bytes ("\0")
         between them.

   Examples:
   - [[http://dev.qtranslate.org/api-examples-php/translations/add.php]]
   - [[http://info.qtranslate.org/api-examples-js/#translations/add.js]]


** like

   Add a like for the given translation.

   + POST api/translations/like ::
     - tguid :: ID of the translation

   Examples:
   - [[http://dev.qtranslate.org/api-examples-php/translations/like.php]]
   - [[http://info.qtranslate.org/api-examples-js/#translations/like.js]]


** del

   Delete a translation

   + POST api/translations/del ::
     - tguid :: ID of the translation

   Examples:
   - [[http://dev.qtranslate.org/api-examples-php/translations/add.php]]
   - [[http://info.qtranslate.org/api-examples-js/#translations/add.js]]


** search

   Search strings and translations using various filters.

   + GET api/translations :: This provides the same
     functionality and has the same parameters as the *search*
     operation.  The only difference is that the parameters are
     provided as a GET request (in the URL), whereas the parameters of
     'search' are provided as a POST request. Sometimes this may be
     more convenient.

   + POST api/translations/search ::
     - lng ::
         The language of translations.
     - limit ::
         The number of results to be returned (min: 5, max: 50).
     - words ::
         Words to be searched for.
     - sguid ::
         If the /words/ is empty and there is a /sguid/ then the
         words of this string are used for searching.
     - mode ::
         Search mode. Can be one of:
         - natural-strings :       Natural search on strings (default).
         - natural-translations :  Natural search on translations.
         - boolean-strings :       Boolean search on strings.
         - boolean-translations :  Boolean search on translations.
     - page ::
         Page of results to be displayed.
     - project ::
         Limit search only to this project
     - origin ::
         Limit search only to the projects of this origin.
     - only_mine :: (boolean)
         Limit search only to the strings touched (translated or voted)
         by the current user.
     - translated_by ::
         Limit search by the author of translations
         (can be used only by admins).
     - voted_by ::
         Limit search by a voter (can be used only by admins).
     - date_filter ::
         Which date to filter (used only by admins). Can be one of:
         - strings :       Filter Strings By Date
         - translations :  Filter Translations By Date (default)
         - votes :         Filter Votes By Date
     - from_date ::
         Date and time.
     - to_date ::
         Date and time.
     - list_mode ::
         Used when listing the strings of a project.
         Can be one of: /all/, /translated/, /untranslated/

  + GET translations/search :: Search strings and translations using
    various filters.  If the request header =Accept: application/json=
    is set, then the output will be in JSON (otherwise it will be an
    HTML page). It gets the same parameters as =GET
    api/translations=

  Examples:
  - [[http://dev.qtranslate.org/api-examples-php/translations/search.php]]
  - [[http://info.qtranslate.org/api-examples-js/#translations/list.js]]
  - [[http://info.qtranslate.org/api-examples-js/#translations/search.js]]

  #+BEGIN_EXAMPLE
  curl -k -H 'Accept: application/json' \
       'http://dev.qtranslate.org/translations/search?lng=sq&words=space'
  curl -k -H 'Accept: application/json' \
       'https://sq.btranslate.net/translations/search?lng=sq&words=space'
  #+END_EXAMPLE


** submit

   Submit multiple actions at once.

   + POST api/translations/submit ::
         Array of actions. Each action is an associated array
         that contains the items:
         - action ::
             The action to be done: =add | vote | del | del_vote=
         - params ::
             Associative array of the needed parameters for this action.

   Examples:
   - [[http://dev.qtranslate.org/api-examples-php/translations/submit.php]]
   - [[http://info.qtranslate.org/api-examples-js/#translations/submit.js]]


** import

   Import translations from PO files.

   + POST api/translations/import ::
     - lng ::
         Language of translations.
     - file ::
         A PO file with translations, or an archive of PO files
         (accepted extensions: .tar, .gz, .tgz, .bz2, .xz, .7z, .zip).

     Returns associative array containing:
     - messages ::
         Array of notification messages; each notification message
         is an array of a message and a type, where type can be one of
         =status=, =warning=, =error=.

   This is like a bulk translation and voting service. For any
   translation in the PO files, it will be added as a suggestion if
   such a translation does not exist, or it will just be voted if such
   a translation already exists. In case that the translation already
   exists but its author is not known, then you (the user who makes
   the import) will be recorded as the author of the translation.

   This can be useful for translators if they prefer to work off-line
   with PO files. They can export the PO files of a project, work on
   them with desktop tools (like Lokalize) to translate or correct
   exported translations, and then import back to Q-Translate the
   translated/corrected PO files.

   Examples:
   - [[http://dev.qtranslate.org/api-examples-php/translations/import.php]]
   - [[http://info.qtranslate.org/api-examples-js/#translations/import.js]]


* misc


** latest

   + GET latest/$lng :: Return the latest translations in JSON format.
        Latest means since yesterday.  Results are cached, so last minute
        translations may not appear on the list.
     - lng :: The language of translations.

   Examples:
   - [[https://dev.qtranslate.org/api-examples-php/misc/latest.php]]
   - [[http://info.qtranslate.org/api-examples-js/#misc/latest.js]]

   #+BEGIN_EXAMPLE
   curl https://qtranslate.org/latest/en | python -m json.tool
   curl https://en.btranslate.net/qtr/latest | python -m json.tool
   #+END_EXAMPLE


** rss-feed

   + GET rss-feed/$lng :: Return a RSS feed of the latest translations.
        Latest means since yesterday.  Results are cached, so last minute
        translations may not appear on the list.
     - lng :: The language of translations.

   Examples:
   - [[https://dev.qtranslate.org/api-examples-php/misc/rss-feed.php]]
   - [[http://info.qtranslate.org/api-examples-js/#misc/rss-feed.js]]

   #+BEGIN_EXAMPLE
   curl https://qtranslate.org/rss-feed/sq | python -m json.tool
   curl https://en.btranslate.net/qtr/rss-feed | python -m json.tool
   #+END_EXAMPLE


** autouser

   + GET auto/user/$lng/$str :: Retrieve a JSON list of autocomplete
        suggestions for users.
     - lng :: Language of translations.
     - str :: Beginning of a user name.

   Examples:
   - [[https://dev.qtranslate.org/api-examples-php/misc/autouser.php]]
   - [[http://info.qtranslate.org/api-examples-js/#misc/autouser.js]]

   #+BEGIN_EXAMPLE
   curl https://qtranslate.org/auto/user/sq/d
   #+END_EXAMPLE


** other

   + GET languages :: Return a json list of languages installed on the
                  system and their details.

   Examples:
   #+BEGIN_EXAMPLE
   curl https://qtranslate.org/languages | python -m json.tool
   #+END_EXAMPLE


* oauth2

  + POST oauth2/token :: Get an OAuth2 token.
    #+BEGIN_EXAMPLE
    $.ajax(base_url + '/oauth2/token', {
        type: 'POST',
        data: {
            grant_type: 'password',
            username: 'user1',
            password: 'pass1',
            scope: 'user_profile', 
        },
        headers: {
            'Authorization': 'Basic ' + btoa(client_id + ':' + client_secret'), 
        },

    });
    #+END_EXAMPLE

  + GET oauth2/tokens/<access_token> :: Verify the validity of an
       OAuth2 token.
    #+BEGIN_EXAMPLE
    $.ajax(base_url + '/oauth2/tokens/' + access_token)
        .fail(function () {
            console.log('Token is not valid.');
        })
        .done(function (response) {
            console.log(response);
        });
    #+END_EXAMPLE

  + POST oauth2/user/profile :: Get the profile of the user.
    #+BEGIN_EXAMPLE
    $.ajax(base_url + '/oauth2/user/profile', {
        type: 'POST',
        headers: {
            'Authorization': 'Bearer ' + access_token,
        },
        dataType: 'json',
    });
    #+END_EXAMPLE

  Examples:
  - [[http://info.qtranslate.org/api-examples-js/#oauth2/get_token.js]]
  - [[http://info.qtranslate.org/api-examples-js/#oauth2/verify_token.js]]
  - [[http://info.qtranslate.org/api-examples-js/#oauth2/get_user_profile.js]]

  For more details and examples see: https://github.com/dashohoxha/oauth2-js

  For PHP examples see:
  - https://qtranslate.org/api-examples-php/config.php
  - https://qtranslate.org/api-examples-php/get_access_token.php
  - https://qtranslate.org/api-examples-php/translations/add.php

